---
- hosts: cp*
  sudo: yes
  tasks:
    - name: Copy userdata file
      copy: src=files/userdata.txt dest=/tmp/userdata.sh mode=755
    - name: Run shell on background
      shell: bash /tmp/userdata.sh
      async: 300
      poll: 0
      register: userdata_status
    - name: Check job
      async_status: jid={{ userdata_status.ansible_job_id }}
      register: job_result
      until: job_result.finished
      retries: 100

